- name: configure kubernetes master and worker nodes
  hosts: all
  remote_user: root
  become: yes
  gather_facts: yes
  roles:
    - users
    - docker
    - firewall
    - kube-depend
    


- name:	deploy kubernetes master 
  hosts: master
  remote_user: root
  become: yes
  gather_facts: yes
  roles:
   - kubernetes
