
  - name: firewalld master rules
    firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
    with_items:
          - 6443/tcp
          - 10250/tcp
          - 2379-2380/tcp
          - 10251/tcp
          - 10252/tcp
          - 10255/tcp
    notify:
    - reload service firewalld

